# Generated by Django 3.0.8 on 2020-07-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200710_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
