# Generated by Django 3.0.8 on 2020-07-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backgroundimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
