# Generated by Django 3.0.8 on 2020-07-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200710_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortintro', models.CharField(default='I am a curious B.tech Computer science undergraduate from KIIT UNIVERSITY, Bhubaneswar. Data Science and Web Development Enthusiast.', max_length=200)),
                ('quality1', models.CharField(default='Web developer', max_length=20)),
                ('quality2', models.CharField(default='Data scientist', max_length=20)),
                ('aboutquality', models.CharField(default='Data Science is the process of analyzing data using specialized skills and technology whereas Web Development is the creation of a website for the internet or intranet using company details, client requirement, and technical skills.', max_length=20)),
                ('phone', models.IntegerField(default='9996143731')),
                ('city', models.CharField(default='Narnaul', max_length=20)),
                ('age', models.IntegerField(default='21')),
                ('degree', models.CharField(default='B.Tech', max_length=20)),
                ('email', models.EmailField(default='kdsastm@gmail.com', max_length=200)),
            ],
        ),
    ]
