# Generated by Django 3.0.8 on 2020-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutquality',
            field=models.CharField(default='Data Science is the process of analyzing data using specialized skills and technology whereas Web Development is the creation of a website for the internet or intranet using company details, client requirement, and technical skills.', max_length=400),
        ),
       
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(default='+919996143731', max_length=13),
        ),
    ]
