# Generated by Django 3.0.8 on 2020-07-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200710_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
