# Generated by Django 3.0.8 on 2020-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_about'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
