# Generated by Django 3.0.8 on 2020-07-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20200710_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='birthday',
            field=models.DateField(default='1999-01-21'),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(default='+919996143731', max_length=13),
        ),
    ]
