# Generated by Django 3.0.8 on 2020-07-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20200710_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='intro',
            field=models.CharField(default='I am a curious B.tech Computer science undergraduate from KIIT UNIVERSITY, Bhubaneswar. Data Science and Web Development Enthusiast.', max_length=500),
        ),
    ]
