# Generated by Django 3.0.8 on 2020-07-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_about_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutquality',
            field=models.CharField(blank=True, default='Data Science is the process of analyzing data using specialized skills and technology whereas Web Development is the creation of a website for the internet or intranet using company details, client requirement, and technical skills.', max_length=400),
        ),
        migrations.AlterField(
            model_name='about',
            name='intro',
            field=models.CharField(blank=True, default='I am a curious B.tech Computer science undergraduate from KIIT UNIVERSITY, Bhubaneswar. Data Science and Web Development Enthusiast.', max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='quality2',
            field=models.CharField(blank=True, default='Data scientist', max_length=20),
        ),
    ]
