# Generated by Django 3.0.8 on 2020-07-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_summary'),
    ]

    operations = [
       
    ]
