# Generated by Django 3.0.8 on 2020-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_remove_summary_resumeemail'),
    ]

    operations = [
      
    ]
