# Generated by Django 3.0.8 on 2020-07-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_summary_resumeemail'),
    ]

    operations = [
        
    ]
