# Generated by Django 3.0.8 on 2020-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_remove_summary_resumeemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='resumeemail',
            field=models.EmailField(blank=True, default='kdsastm@gmail.com', max_length=200),
        ),
    ]
