# Generated by Django 3.0.8 on 2020-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_summary_resumeemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='resumeintro',
            field=models.CharField(blank=True, default='Optimizing problems by thinking out of the box. A learning enthusiast grasping and observing patterns in day-to-day activities. I am comfortable with a lot of tech languages & frameworks and would love to work in a very dynamic & aspirational environment. Passionate about Competitive programming, Algorithms, Data Science and Web Development. Playing badminton and Cooking being the favorite pastime.', max_length=500),
        ),
    ]
