# Generated by Django 3.0.8 on 2020-07-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+919996143731', max_length=13)),
                ('location', models.CharField(default='Narnaul,Haryana,India ', max_length=100)),
                ('email', models.EmailField(default='kdsastm@gmail.com', max_length=100)),
                ('maplink', models.URLField(blank=True, default='https://maps.google.com/maps?q=narnaul%20haryana&t=&z=13&ie=UTF8&iwloc=&output=embed', max_length=1000)),
            ],
        ),
    ]
